git-ssh

diff --git a/src/setup/git-ssh b/src/setup/git-ssh
--- a/src/setup/git-ssh
+++ b/src/setup/git-ssh
@@ -1,12 +1,14 @@
 #!/bin/sh
 # see https://github.com/kubernetes/git-sync/blob/release-3.x/docs/ssh.md
 
-set -e
+set -ex
 dest=target/ssh
 secret=git-creds
 mkdir -p $dest
-ssh-keyscan mops.schmizzolin.de > $dest/known_hosts
+ssh-keyscan -4 mops.schmizzolin.de > $dest/known_hosts || (echo "ssh-keyscan failed"; exit 1)
 cp $HOME/.ssh/id_rsa $dest/
 ssh-keygen -p -f $dest/id_rsa
 kubectl create secret generic $secret --from-file=ssh=$dest/id_rsa --from-file=known_hosts=$dest/known_hosts
 rm -rf $dest
+echo done
+
